const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Pincode = require('./src/modules/delivery/pincode.model');

dotenv.config();

const pincodeData = [
  // ── Other Major Cities ──────────────────────
  { pincode: '110001', city: 'Delhi', state: 'Delhi', estimatedDays: 2, isAvailable: true },
  { pincode: '400001', city: 'Mumbai', state: 'Maharashtra', estimatedDays: 3, isAvailable: true },
  { pincode: '560001', city: 'Bangalore', state: 'Karnataka', estimatedDays: 3, isAvailable: true },
  { pincode: '600001', city: 'Chennai', state: 'Tamil Nadu', estimatedDays: 4, isAvailable: true },
  { pincode: '700001', city: 'Kolkata', state: 'West Bengal', estimatedDays: 4, isAvailable: true },
  { pincode: '500001', city: 'Hyderabad', state: 'Telangana', estimatedDays: 3, isAvailable: true },
  { pincode: '800001', city: 'Patna', state: 'Bihar', estimatedDays: 5, isAvailable: true },
  { pincode: '380001', city: 'Ahmedabad', state: 'Gujarat', estimatedDays: 4, isAvailable: true },

  // ── Andhra Pradesh – Visakhapatnam District ──
  { pincode: '530001', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '530002', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '530003', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '530004', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '530016', city: 'Visakhapatnam', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '531001', city: 'Narsipatnam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '531021', city: 'Chodavaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '531055', city: 'Araku Valley', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '531061', city: 'Bheemunipatnam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '531084', city: 'Yellamanchili', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },

  // ── Andhra Pradesh – Vizianagaram District ──
  { pincode: '535001', city: 'Vizianagaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '535002', city: 'Vizianagaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '535003', city: 'Vizianagaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '535101', city: 'Bobbili', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '535145', city: 'Salur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Srikakulam District ──
  { pincode: '532001', city: 'Srikakulam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '532005', city: 'Srikakulam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '532201', city: 'Narasannapeta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '532221', city: 'Palasa', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '532401', city: 'Tekkali', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '532421', city: 'Amadalavalasa', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – East Godavari District ──
  { pincode: '533001', city: 'Kakinada', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '533003', city: 'Kakinada', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '533101', city: 'Rajahmundry', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '533103', city: 'Rajahmundry', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '533104', city: 'Rajahmundry', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '533201', city: 'Amalapuram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '533210', city: 'Mummidivaram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '533216', city: 'Ramachandrapuram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '533237', city: 'Mandapeta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '533253', city: 'Pithapuram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '533261', city: 'Tuni', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },

  // ── Andhra Pradesh – West Godavari District ──
  { pincode: '534001', city: 'Eluru', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534003', city: 'Eluru', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534101', city: 'Tadepalligudem', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534176', city: 'Tanuku', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534201', city: 'Bhimavaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534202', city: 'Bhimavaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '534210', city: 'Narasapuram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '534301', city: 'Jangareddygudem', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '534350', city: 'Nidadavole', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '534401', city: 'Kovvur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '534450', city: 'Palacole', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Krishna District ──
  { pincode: '520001', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '520002', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '520003', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '520004', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '520007', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '520010', city: 'Vijayawada', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '521001', city: 'Machilipatnam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '521002', city: 'Machilipatnam', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '521101', city: 'Nuzvid', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '521110', city: 'Kaikalur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '521131', city: 'Gudivada', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '521301', city: 'Jaggayyapeta', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '521333', city: 'Nandigama', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '521366', city: 'Tiruvuru', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '521401', city: 'Vuyyuru', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '521456', city: 'Avanigadda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Guntur District ──
  { pincode: '522001', city: 'Guntur', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '522002', city: 'Guntur', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '522003', city: 'Guntur', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '522004', city: 'Guntur', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '522006', city: 'Guntur', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '522101', city: 'Bapatla', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522111', city: 'Repalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '522201', city: 'Tenali', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522202', city: 'Tenali', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522301', city: 'Sattenapalle', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522401', city: 'Ponnur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '522501', city: 'Vinukonda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '522601', city: 'Narasaraopet', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522603', city: 'Narasaraopet', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '522611', city: 'Macherla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Prakasam District ──
  { pincode: '523001', city: 'Ongole', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '523002', city: 'Ongole', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '523101', city: 'Kandukur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '523105', city: 'Chirala', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '523155', city: 'Chirala', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '523201', city: 'Addanki', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '523225', city: 'Markapur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '523241', city: 'Giddalur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '523261', city: 'Podili', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '523271', city: 'Martur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '523301', city: 'Darsi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Nellore District ──
  { pincode: '524001', city: 'Nellore', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524002', city: 'Nellore', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524003', city: 'Nellore', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524004', city: 'Nellore', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524101', city: 'Atmakur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '524121', city: 'Kovur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '524131', city: 'Kavali', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524201', city: 'Gudur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524221', city: 'Venkatagiri', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '524301', city: 'Sullurpeta', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524321', city: 'Naidupeta', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524341', city: 'Tada', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '524401', city: 'Podalakur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '524421', city: 'Alluru', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Chittoor District ──
  { pincode: '517001', city: 'Chittoor', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517002', city: 'Chittoor', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517101', city: 'Nagari', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517102', city: 'Nagari', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517127', city: 'Srikalahasti', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517201', city: 'Madanapalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517214', city: 'Punganur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517301', city: 'Piler', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517325', city: 'Palamaner', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517391', city: 'Kuppam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517401', city: 'Puttur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517501', city: 'Tirupati', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517502', city: 'Tirupati', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517503', city: 'Tirupati', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517504', city: 'Tirupati', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517507', city: 'Tirupati', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517520', city: 'Tirupati Urban', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517526', city: 'Chittoor Rural', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517541', city: 'Chandragiri', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517551', city: 'Renigunta', state: 'Andhra Pradesh', estimatedDays: 3, isAvailable: true },
  { pincode: '517561', city: 'Srinivasapuram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517571', city: 'Pakala', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517581', city: 'Gudupalle', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '517590', city: 'Vayalpadu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '517601', city: 'Thamballapalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Kadapa District ──
  { pincode: '516001', city: 'Kadapa', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516002', city: 'Kadapa', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516003', city: 'Kadapa', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516101', city: 'Proddatur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516360', city: 'Proddatur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516126', city: 'Badvel', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516150', city: 'Jammalamadugu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516175', city: 'Rajampet', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516193', city: 'Mydukur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516203', city: 'Rayachoti', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516213', city: 'Pulivendula', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516227', city: 'Vempalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516257', city: 'Kamalapuram', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516267', city: 'Giddalur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516301', city: 'Yerraguntla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516321', city: 'Porumamilla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516329', city: 'Mydukur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516401', city: 'Mydukur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516411', city: 'Sidhout', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516416', city: 'Cuddapah', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '516421', city: 'Vontimitta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516431', city: 'Rajampet', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516434', city: 'Duvvuru', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516439', city: 'Chakrayapet', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516444', city: 'Obulavaripalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516454', city: 'Dornala', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516464', city: 'Reddipalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516474', city: 'Chitvel', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516484', city: 'Khajipet', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516494', city: 'Veerapunayani Palle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '516501', city: 'Betamcherla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Kurnool District ──
  { pincode: '518001', city: 'Kurnool', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518002', city: 'Kurnool', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518003', city: 'Kurnool', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518004', city: 'Kurnool', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518005', city: 'Kurnool', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518101', city: 'Nandyal', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518501', city: 'Nandyal', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518502', city: 'Nandyal', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518301', city: 'Adoni', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518302', city: 'Adoni', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '518201', city: 'Dhone', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518220', city: 'Panyam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518225', city: 'Gospadu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518352', city: 'Kowthalam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518395', city: 'Mantralayam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518401', city: 'Yemmiganur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518405', city: 'Kosigi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518411', city: 'Alur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518463', city: 'Allagadda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '518467', city: 'Srisailam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },

  // ── Andhra Pradesh – Anantapur District ──
  { pincode: '515001', city: 'Anantapur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515002', city: 'Anantapur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515003', city: 'Anantapur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515004', city: 'Anantapur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515101', city: 'Tadipatri', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515115', city: 'Pamidi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515134', city: 'Guntakal', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515201', city: 'Hindupur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515202', city: 'Hindupur', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515211', city: 'Penukonda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515231', city: 'Madakasira', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515241', city: 'Parigi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515261', city: 'Lepakshi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515271', city: 'Dharmavaram', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515281', city: 'Kadiri', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515301', city: 'Uravakonda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515311', city: 'Rayadurgam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515321', city: 'Gorantla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515331', city: 'Bukkapatnam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515341', city: 'Yadiki', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515401', city: 'Guntakal Town', state: 'Andhra Pradesh', estimatedDays: 4, isAvailable: true },
  { pincode: '515408', city: 'Orvakal', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515411', city: 'Puttaparthi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515413', city: 'Bukkapatnam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515425', city: 'Settur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515445', city: 'Mudigubba', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515455', city: 'Bathalapalli', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515465', city: 'Nambula Pulakunta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515501', city: 'Kanekal', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515511', city: 'Amadagur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515521', city: 'Bommanahal', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515531', city: 'Gandlapenta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515541', city: 'Somandepalli', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515551', city: 'Roddam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515561', city: 'Rolla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515571', city: 'Kambadur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515581', city: 'Vajrakarur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515591', city: 'Nallamada', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515601', city: 'Beluguppa', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515611', city: 'Kalyandurg', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515621', city: 'Gumagatta', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515631', city: 'Atmakur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515641', city: 'Gownipatla', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515651', city: 'Kundurpi', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515661', city: 'Kuderu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515671', city: 'Chilamathur', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515701', city: 'Rayadurgam', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515711', city: 'Rapthadu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515721', city: 'Agali', state: 'Andhra Pradesh', estimatedDays: 6, isAvailable: true },
  { pincode: '515731', city: 'Kuderu', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515741', city: 'Gudibanda', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515751', city: 'Obular', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515761', city: 'Narpala', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515801', city: 'Kanaganapalle', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
  { pincode: '515811', city: 'Tanakal', state: 'Andhra Pradesh', estimatedDays: 5, isAvailable: true },
];

async function seedPincodes() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing pincodes
    await Pincode.deleteMany({});
    console.log('Cleared existing pincodes');

    // Insert new pincodes
    await Pincode.insertMany(pincodeData);
    console.log('Seeded pincodes successfully');

    process.exit(0);
  } catch (error) {
    console.error('Error seeding pincodes:', error);
    process.exit(1);
  }
}

seedPincodes();
